"""adicionar atualizado_em em usuarios

Revision ID: a2352dddc5bd
Revises: 0dc9f15c96bb
Create Date: 2026-08-24 13:34:25.851044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2352dddc5bd'
down_revision: Union[str, Sequence[str], None] = '0dc9f15c96bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('atualizado_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'atualizado_em')
    # ### end Alembic commands ###
