"""gabinete_email_institucional_e_diario

Revision ID: d7852c6d0c1c
Revises: 514ce097e4cd
Create Date: 2026-08-27 14:20:03.908426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7852c6d0c1c'
down_revision: Union[str, Sequence[str], None] = '514ce097e4cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gabinetes', sa.Column('email_institucional', sa.String(length=150), nullable=True))
    op.add_column('gabinetes', sa.Column('ultimo_email_diario_data', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gabinetes', 'ultimo_email_diario_data')
    op.drop_column('gabinetes', 'email_institucional')
    # ### end Alembic commands ###
