"""baseline: schema atual com multi-tenant

Revision ID: da30883281a3
Revises: 
Create Date: 2026-08-24 12:51:06.256713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da30883281a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gabinetes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gabinete_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['gabinete_id'], ['gabinetes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_gabinete_id'), 'categorias', ['gabinete_id'], unique=False)
    op.create_table('eleitores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gabinete_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('apelido', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('titulo_eleitor', sa.String(length=12), nullable=True),
    sa.Column('zona_eleitoral', sa.String(length=10), nullable=True),
    sa.Column('ref_historico', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['gabinete_id'], ['gabinetes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eleitores_gabinete_id'), 'eleitores', ['gabinete_id'], unique=False)
    op.create_index(op.f('ix_eleitores_id'), 'eleitores', ['id'], unique=False)
    op.create_index(op.f('ix_eleitores_nome'), 'eleitores', ['nome'], unique=False)
    op.create_table('membros_gabinete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('gabinete_id', sa.Integer(), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['gabinete_id'], ['gabinetes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'gabinete_id', name='uq_membro_usuario_gabinete')
    )
    op.create_table('subcategorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demandas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gabinete_id', sa.Integer(), nullable=True),
    sa.Column('eleitor_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=60), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('subcategoria_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('secretaria', sa.String(length=100), nullable=True),
    sa.Column('prioridade', sa.String(length=30), nullable=True),
    sa.Column('responsavel', sa.String(length=150), nullable=True),
    sa.Column('data_abertura', sa.DateTime(), nullable=True),
    sa.Column('prazo', sa.Date(), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.Column('observacoes_internas', sa.Text(), nullable=True),
    sa.Column('ref_historico', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['eleitor_id'], ['eleitores.id'], ),
    sa.ForeignKeyConstraint(['gabinete_id'], ['gabinetes.id'], ),
    sa.ForeignKeyConstraint(['subcategoria_id'], ['subcategorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demandas_gabinete_id'), 'demandas', ['gabinete_id'], unique=False)
    op.create_table('agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gabinete_id', sa.Integer(), nullable=True),
    sa.Column('eleitor_id', sa.Integer(), nullable=True),
    sa.Column('demanda_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('local', sa.String(length=150), nullable=True),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fim', sa.DateTime(), nullable=True),
    sa.Column('responsavel', sa.String(length=150), nullable=True),
    sa.Column('telefone_contato', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('ref_historico', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['demanda_id'], ['demandas.id'], ),
    sa.ForeignKeyConstraint(['eleitor_id'], ['eleitores.id'], ),
    sa.ForeignKeyConstraint(['gabinete_id'], ['gabinetes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenda_gabinete_id'), 'agenda', ['gabinete_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agenda_gabinete_id'), table_name='agenda')
    op.drop_table('agenda')
    op.drop_index(op.f('ix_demandas_gabinete_id'), table_name='demandas')
    op.drop_table('demandas')
    op.drop_table('subcategorias')
    op.drop_table('membros_gabinete')
    op.drop_index(op.f('ix_eleitores_nome'), table_name='eleitores')
    op.drop_index(op.f('ix_eleitores_id'), table_name='eleitores')
    op.drop_index(op.f('ix_eleitores_gabinete_id'), table_name='eleitores')
    op.drop_table('eleitores')
    op.drop_index(op.f('ix_categorias_gabinete_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('gabinetes')
    # ### end Alembic commands ###
